# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import pytest

from hammunition_hill.adif import US_STATES, build_index, mode_group, normalize_band, parse_adif
from hammunition_hill.prefix import PrefixTable

LOG = """Generated by SomeLogger
<PROGRAMID:10>SomeLogger
<EOH>
<CALL:4>W1AW<BAND:3>20M<MODE:3>SSB<QSO_DATE:8>20260101<EOR>
<CALL:6>DL1ABC<BAND:3>40M<MODE:2>CW<QSO_DATE:8>20260102<QSL_RCVD:1>Y<EOR>
<CALL:6>JA1ABC<BAND:3>20M<MODE:3>FT8<QSO_DATE:8>20260103<EOR>
<CALL:6>VK2ABC<BAND:3>15M<MODE:4>RTTY<QSO_DATE:8>20260104<LOTW_QSL_RCVD:1>Y<EOR>
"""


@pytest.fixture
def table():
    return PrefixTable(None)


@pytest.fixture
def index(table):
    return build_index(LOG, table)


# --- parsing ------------------------------------------------------------
def test_parses_every_record():
    assert len(list(parse_adif(LOG))) == 4


def test_header_is_skipped():
    """PROGRAMID lives above <EOH> and must not become a QSO."""
    first = next(parse_adif(LOG))
    assert first["CALL"] == "W1AW"


def test_field_lengths_are_honoured():
    """ADIF is length-prefixed, not delimited -- a value may contain anything."""
    record = next(parse_adif("<CALL:9>W1AW<BAD><BAND:3>20M<EOR>"))
    assert record["CALL"] == "W1AW<BAD>"


def test_tags_are_case_insensitive():
    record = next(parse_adif("<call:4>W1AW<band:3>20M<eor>"))
    assert record["CALL"] == "W1AW"


def test_a_file_with_no_header_still_parses():
    assert len(list(parse_adif("<CALL:4>W1AW<EOR>"))) == 1


def test_trailing_record_without_eor_is_kept():
    records = list(parse_adif("<CALL:4>W1AW<EOR><CALL:6>DL1ABC"))
    assert [r["CALL"] for r in records] == ["W1AW", "DL1ABC"]


def test_empty_input():
    assert list(parse_adif("")) == []


def test_unwanted_fields_are_dropped():
    record = next(parse_adif("<CALL:4>W1AW<RST_SENT:2>59<EOR>"))
    assert "RST_SENT" not in record


# --- normalization ------------------------------------------------------
def test_band_case_is_normalized():
    assert normalize_band("20M") == "20m"


@pytest.mark.parametrize(
    "mode,group",
    [
        ("SSB", "PHONE"),
        ("USB", "PHONE"),
        ("FM", "PHONE"),
        ("CW", "CW"),
        ("FT8", "DIGITAL"),
        ("RTTY", "DIGITAL"),
        ("JS8", "DIGITAL"),
    ],
)
def test_mode_groups(mode, group):
    assert mode_group(mode) == group


def test_unknown_mode_passes_through():
    assert mode_group("SSTV") == "SSTV"


# --- the index ----------------------------------------------------------
def test_counts(index):
    assert index.qso_count == 4
    assert index.unresolved == 0


def test_entities_indexed(index):
    assert index.entities == {"United States", "Germany", "Japan", "Australia"}


def test_confirmation_is_tracked_separately(index):
    assert index.confirmed_entities == {"Germany", "Australia"}


def test_worked_entity_on_worked_band_is_not_needed(index):
    status = index.status("United States", "20m", "SSB")
    assert status["new_entity"] is False
    assert status["new_band"] is False
    assert status["new_mode"] is False


def test_new_entity(index):
    status = index.status("Brazil", "20m", "SSB")
    assert status["new_entity"] is True


def test_new_band_slot(index):
    """Germany worked on 40m CW. On 20m it is a band slot, not a new entity."""
    status = index.status("Germany", "20m", "CW")
    assert status["new_entity"] is False
    assert status["new_band"] is True
    assert status["new_mode"] is False


def test_new_mode_slot(index):
    """Japan worked on 20m FT8. Same band in SSB is a new mode group."""
    status = index.status("Japan", "20m", "SSB")
    assert status["new_entity"] is False
    assert status["new_band"] is False
    assert status["new_mode"] is True


def test_modes_in_the_same_group_do_not_count_as_new(index):
    """FT8 and RTTY are both DIGITAL -- chasing digital, you already have it."""
    assert index.status("Japan", "20m", "RTTY")["new_mode"] is False
    assert index.status("Australia", "15m", "FT8")["new_mode"] is False


def test_ssb_and_fm_are_the_same_slot(index):
    assert index.status("United States", "20m", "FM")["new_mode"] is False


def test_unknown_entity_is_not_claimed_as_needed(index):
    """A spot we could not resolve must not be coloured as a new one."""
    status = index.status(None, "20m", "SSB")
    assert status["known"] is False
    assert status["new_entity"] is False


def test_unresolvable_callsigns_are_counted(table):
    index = build_index("<CALL:5>!!!!!<BAND:3>20M<EOR>", table)
    assert index.qso_count == 1
    assert index.unresolved == 1


def test_records_without_a_call_are_skipped(table):
    index = build_index("<BAND:3>20M<EOR>", table)
    assert index.qso_count == 0


def test_submode_takes_priority_over_mode(table):
    """Loggers write MODE=MFSK SUBMODE=FT4; the submode is the useful one."""
    index = build_index("<CALL:4>W1AW<BAND:3>20M<MODE:4>MFSK<SUBMODE:3>FT4<EOR>", table)
    assert ("United States", "DIGITAL") in index.entity_mode


# --- Worked All States ---------------------------------------------------
def test_states_are_indexed_from_the_state_field(table):
    index = build_index(
        "<CALL:4>W6BB<BAND:3>20M<STATE:2>CA<LOTW_QSL_RCVD:1>Y<EOR>"
        "<CALL:5>K1ABC<BAND:3>40M<STATE:2>ct<EOR>",
        table,
    )
    assert index.states == {"CA", "CT"}
    assert index.confirmed_states == {"CA"}


def test_a_canadian_province_does_not_count_toward_was(table):
    """VE logs carry STATE=ON; Ontario toward WAS would be flattering and wrong."""
    index = build_index("<CALL:5>VE3XY<BAND:3>20M<STATE:2>ON<EOR>", table)
    assert index.states == set()


def test_a_state_counts_even_when_the_call_does_not_resolve(table):
    """WAS credit rides on the log, not on the prefix lookup."""
    index = build_index("<CALL:5>!!!!!<BAND:3>20M<STATE:2>WY<EOR>", table)
    assert index.unresolved == 1
    assert index.states == {"WY"}


def test_the_us_state_list_is_exactly_fifty():
    """DC is deliberately absent -- ARRL counts it as Maryland for WAS."""
    assert len(US_STATES) == 50
    assert "DC" not in US_STATES


def test_the_entity_denominator_is_plausible(table):
    """A few hundred entities; a broken count reads 0 or tens of thousands."""
    assert 200 < table.entity_count < 500
